// Generated by shader_port.py from the game pair of shader key 0x00effe. Do not edit.
float4 cMVP[4] : register(c4);
float4 cVP[4] : register(c8);
float4 cModel0[3] : register(c58);
struct VS_INPUT {
    float4 position : POSITION;
};
struct VS_OUTPUT {
    float4 position : POSITION;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    float4 A_POSITION0 = float4(i.position.xyz, 1);
    float4 M_g_matWorldViewProj[4];
    M_g_matWorldViewProj[0] = float4(cMVP[0].x, cMVP[1].x, cMVP[2].x, cMVP[3].x);
    M_g_matWorldViewProj[1] = float4(cMVP[0].y, cMVP[1].y, cMVP[2].y, cMVP[3].y);
    M_g_matWorldViewProj[2] = float4(cMVP[0].z, cMVP[1].z, cMVP[2].z, cMVP[3].z);
    M_g_matWorldViewProj[3] = float4(cMVP[0].w, cMVP[1].w, cMVP[2].w, cMVP[3].w);
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vr0 = 0;
    vr0.xyzw = (A_POSITION0.yyyy * float4(M_g_matWorldViewProj[1].x, M_g_matWorldViewProj[1].y, M_g_matWorldViewProj[1].z, M_g_matWorldViewProj[1].w)).xyzw;
    vr0.xyzw = (A_POSITION0.xxxx * float4(M_g_matWorldViewProj[0].x, M_g_matWorldViewProj[0].y, M_g_matWorldViewProj[0].z, M_g_matWorldViewProj[0].w) + vr0.xyzw).xyzw;
    vr0.xyzw = (A_POSITION0.zzzz * float4(M_g_matWorldViewProj[2].x, M_g_matWorldViewProj[2].y, M_g_matWorldViewProj[2].z, M_g_matWorldViewProj[2].w) + vr0.xyzw).xyzw;
    vo0.xyzw = (vr0.xyzw + float4(M_g_matWorldViewProj[3].x, M_g_matWorldViewProj[3].y, M_g_matWorldViewProj[3].z, M_g_matWorldViewProj[3].w)).xyzw;
    o.position = vo0;
    return o;
}
