// Generated by shader_port.py from the game pair of shader key 0x01f002. Do not edit.
float4 cMVP[4] : register(c4);
float4 cVP[4] : register(c8);
float4 cModel[53] : register(c58);
struct VS_INPUT {
    float4 position : POSITION;
    float4 boneWeights : BLENDWEIGHT;
    float4 boneIndices : BLENDINDICES;
    float2 uv0 : TEXCOORD0;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    int4 bi = D3DCOLORtoUBYTE4(i.boneIndices) * 3;
    float2 bw = (i.boneWeights.xy + 1.0) / 32768.0;
    float3x4 skin = float3x4(cModel[bi.x], cModel[bi.x + 1], cModel[bi.x + 2]) * bw.x + float3x4(cModel[bi.y], cModel[bi.y + 1], cModel[bi.y + 2]) * bw.y + float3x4(cModel[bi.z], cModel[bi.z + 1], cModel[bi.z + 2]) * (1 - bw.x - bw.y);
    float4 A_POSITION0 = float4(mul(skin, float4(i.position.xyz, 1)), 1);
    float4 A_COLOR0 = float4(1, 1, 1, 1);
    float4 A_TEXCOORD0 = float4(i.uv0, 0, 1);
    float4 M_g_matWorldViewProj[4];
    M_g_matWorldViewProj[0] = float4(cVP[0].x, cVP[1].x, cVP[2].x, cVP[3].x);
    M_g_matWorldViewProj[1] = float4(cVP[0].y, cVP[1].y, cVP[2].y, cVP[3].y);
    M_g_matWorldViewProj[2] = float4(cVP[0].z, cVP[1].z, cVP[2].z, cVP[3].z);
    M_g_matWorldViewProj[3] = float4(cVP[0].w, cVP[1].w, cVP[2].w, cVP[3].w);
    float U_g_fogParam_0_y = 1;
    float U_g_fogParam_0_x = 0;
    float U_g_fogParam_0_z = 0;
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vo2 = 0;
    float4 vr0 = 0;
    vr0.xyzw = (A_POSITION0.yyyy * float4(M_g_matWorldViewProj[1].x, M_g_matWorldViewProj[1].y, M_g_matWorldViewProj[1].z, M_g_matWorldViewProj[1].w)).xyzw;
    vr0.xyzw = (A_POSITION0.xxxx * float4(M_g_matWorldViewProj[0].x, M_g_matWorldViewProj[0].y, M_g_matWorldViewProj[0].z, M_g_matWorldViewProj[0].w) + vr0.xyzw).xyzw;
    vr0.xyzw = (A_POSITION0.zzzz * float4(M_g_matWorldViewProj[2].x, M_g_matWorldViewProj[2].y, M_g_matWorldViewProj[2].z, M_g_matWorldViewProj[2].w) + vr0.xyzw).xyzw;
    vr0.xyzw = (A_POSITION0.wwww * float4(M_g_matWorldViewProj[3].x, M_g_matWorldViewProj[3].y, M_g_matWorldViewProj[3].z, M_g_matWorldViewProj[3].w) + vr0.xyzw).xyzw;
    vo0.xyzw = vr0.xyzw.xyzw;
    vr0.x = ((-vr0.wwww) + float4(U_g_fogParam_0_y, 0, 0, 0)).x;
    vo1.w = A_COLOR0.wwww.w;
    vr0.y = ((-float4(0, U_g_fogParam_0_x, 0, 0)) + float4(0, U_g_fogParam_0_y, 0, 0)).y;
    vr0.x = saturate((vr0.xxxx / vr0.yyyy)).x;
    vr0.x = (vr0.xxxx * float4(U_g_fogParam_0_z, 0, 0, 0) + (-float4(U_g_fogParam_0_z, 0, 0, 0))).x;
    vo2.z = (vr0.xxxx + float4(0, 0, 1, 0)).z;
    float K0 = vo1.w;
    float K1 = vo2.z;
    o.position = vo0;
    o.t0 = float4(K0, K1, A_COLOR0.x, A_COLOR0.y);
    o.t1 = float4(A_COLOR0.z, A_TEXCOORD0.x, A_TEXCOORD0.y, 0);
    return o;
}
