// Generated by shader_port.py from the game pair of shader key 0x19f008. Do not edit.
float4 cMVP[4] : register(c4);
float4 cVP[4] : register(c8);
float4 cModel0[3] : register(c58);
struct VS_INPUT {
    float4 position : POSITION;
    float3 normal : NORMAL;
    float4 color : COLOR0;
    float2 uv0 : TEXCOORD0;
    float2 s1 : TEXCOORD1;
    float2 s2 : TEXCOORD2;
    float2 s3 : TEXCOORD3;
    float2 s4 : TEXCOORD4;
    float2 s5 : TEXCOORD5;
    float2 s6 : TEXCOORD6;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float4 t2 : TEXCOORD2;
    float4 t3 : TEXCOORD3;
    float4 t4 : TEXCOORD4;
    float4 t5 : TEXCOORD5;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    float4 A_POSITION0 = float4(i.position.xyz, 1);
    o.position = float4(dot(A_POSITION0, cMVP[0]), dot(A_POSITION0, cMVP[1]), dot(A_POSITION0, cMVP[2]), dot(A_POSITION0, cMVP[3]));
    float4 A_NORMAL0 = float4(i.normal, 0);
    float4 A_COLOR0 = i.color;
    float4 A_TEXCOORD0 = float4(i.uv0, 0, 1);
    float4 M_g_matWorldViewProj[4];
    M_g_matWorldViewProj[0] = float4(cMVP[0].x, cMVP[1].x, cMVP[2].x, cMVP[3].x);
    M_g_matWorldViewProj[1] = float4(cMVP[0].y, cMVP[1].y, cMVP[2].y, cMVP[3].y);
    M_g_matWorldViewProj[2] = float4(cMVP[0].z, cMVP[1].z, cMVP[2].z, cMVP[3].z);
    M_g_matWorldViewProj[3] = float4(cMVP[0].w, cMVP[1].w, cMVP[2].w, cMVP[3].w);
    float3 w0 = float3(cModel0[0].x, cModel0[1].x, cModel0[2].x);
    float3 w1 = float3(cModel0[0].y, cModel0[1].y, cModel0[2].y);
    float3 w2 = float3(cModel0[0].z, cModel0[1].z, cModel0[2].z);
    float3 w3 = float3(cModel0[0].w, cModel0[1].w, cModel0[2].w);
    float det = dot(w0, cross(w1, w2));
    float3 it0 = cross(w1, w2) / det, it1 = cross(w2, w0) / det, it2 = cross(w0, w1) / det;
    float3 vx = normalize(cVP[0].xyz), vy = normalize(cVP[1].xyz), vz = -normalize(cVP[3].xyz);
    float4 M_g_matWorldViewInvTrans[4];
    M_g_matWorldViewInvTrans[0] = float4(dot(it0, vx), dot(it0, vy), dot(it0, vz), 0);
    M_g_matWorldViewInvTrans[1] = float4(dot(it1, vx), dot(it1, vy), dot(it1, vz), 0);
    M_g_matWorldViewInvTrans[2] = float4(dot(it2, vx), dot(it2, vy), dot(it2, vz), 0);
    M_g_matWorldViewInvTrans[3] = float4(0, 0, 0, 1);
    o.t0 = float4(A_COLOR0.x, A_COLOR0.y, A_COLOR0.z, A_COLOR0.w);
    o.t1 = float4(A_TEXCOORD0.x, A_TEXCOORD0.y, A_POSITION0.x * M_g_matWorldViewProj[0].w + A_POSITION0.y * M_g_matWorldViewProj[1].w + A_POSITION0.z * M_g_matWorldViewProj[2].w + A_POSITION0.w * M_g_matWorldViewProj[3].w, A_NORMAL0.x * M_g_matWorldViewInvTrans[0].x + A_NORMAL0.y * M_g_matWorldViewInvTrans[1].x + A_NORMAL0.z * M_g_matWorldViewInvTrans[2].x);
    o.t2 = float4(A_NORMAL0.x * M_g_matWorldViewInvTrans[0].y + A_NORMAL0.y * M_g_matWorldViewInvTrans[1].y + A_NORMAL0.z * M_g_matWorldViewInvTrans[2].y, A_NORMAL0.x * M_g_matWorldViewInvTrans[0].z + A_NORMAL0.y * M_g_matWorldViewInvTrans[1].z + A_NORMAL0.z * M_g_matWorldViewInvTrans[2].z, i.s1.x, i.s1.y);
    o.t3 = float4(i.s2.x, i.s2.y, i.s3.x, i.s3.y);
    o.t4 = float4(i.s4.x, i.s4.y, i.s5.x, i.s5.y);
    o.t5 = float4(i.s6.x, 0, 0, 0);
    return o;
}
