// Generated by shader_port.py from the game pair of shader key 0x00effe. Do not edit.
float4 C0 : register(c0);
float4 C1 : register(c1);
float4 C2 : register(c2);
float4 C3 : register(c3);
struct PS_INPUT {
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vr0 = 0;
    // ---- game vertex program: the part that needs per-draw constants ----
    // ---- game pixel program ----
    float4 po0 = 0;
    float4 po1 = 0;
    po0.xyzw = float4(0, 0, 0, 1).xyzw;
    return po0;
}
