// Generated by shader_port.py from the game pair of shader key 0x00f007. Do not edit.
sampler S0 : register(s0);
float4 C0 : register(c0);
float4 C1 : register(c1);
float4 C2 : register(c2);
float4 C3 : register(c3);
float4 Material0(sampler s, float2 uv, float2 address) { return tex2D(s, uv); }
struct PS_INPUT {
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float4 t2 : TEXCOORD2;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float K0 = i.t0.x;
    float K1 = i.t0.y;
    float K2 = i.t0.z;
    float K3 = i.t0.w;
    float K4 = i.t1.x;
    float A_TEXCOORD0_x = i.t1.y;
    float A_TEXCOORD0_y = i.t1.z;
    float U_g_ambientColor_0_x = i.t1.w;
    float U_g_ambientColor_0_y = i.t2.x;
    float U_g_ambientColor_0_z = i.t2.y;
    float U_g_multColor_0_x = C0.z;
    float U_g_multColor_0_y = C0.w;
    float U_g_multColor_0_z = C1.x;
    float U_g_uvOffset0_0_z = C1.w;
    float U_g_uvOffset0_0_w = C2.x;
    float U_g_uvOffset0_0_x = C1.y;
    float U_g_uvOffset0_0_y = C1.z;
    float U_g_commonParam_0_x = C0.x;
    float U_g_commonParam_0_y = C0.y;
    float U_g_commonParam_0_z = 0.5626704692840576;
    float U_g_commonParam_0_w = 0.08292312920093536;
    float U_port_address0_0_x = 0;
    float U_port_address0_0_y = 0;
    float4 A_TEXCOORD0 = float4(A_TEXCOORD0_x, A_TEXCOORD0_y, 0, 1);
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vo2 = 0;
    float4 vo3 = 0;
    float4 vo4 = 0;
    float4 vr0 = 0;
    // ---- game vertex program: the part that needs per-draw constants ----
    vo1.xyz = (float4(U_g_ambientColor_0_x, U_g_ambientColor_0_y, U_g_ambientColor_0_z, U_g_ambientColor_0_x) * float4(U_g_multColor_0_x, U_g_multColor_0_y, U_g_multColor_0_z, U_g_multColor_0_x)).xyz;
    vo2.xy = (A_TEXCOORD0.xyxx * float4(U_g_uvOffset0_0_z, U_g_uvOffset0_0_w, U_g_uvOffset0_0_z, U_g_uvOffset0_0_z) + float4(U_g_uvOffset0_0_x, U_g_uvOffset0_0_y, U_g_uvOffset0_0_x, U_g_uvOffset0_0_x)).xy;
    vo3.xyzw = float4(U_g_commonParam_0_x, U_g_commonParam_0_y, U_g_commonParam_0_z, U_g_commonParam_0_w).xyzw;
    vo1.w = K0;
    vo2.z = K1;
    vo4.x = K2;
    vo4.y = K3;
    vo4.z = K4;
    // ---- game pixel program ----
    float4 pv1 = vo1;
    float4 pv2 = vo2;
    float4 pv3 = vo3;
    float4 pv4 = vo4;
    float4 po0 = 0;
    float4 po1 = 0;
    float4 pr0 = 0;
    float4 pr1 = 0;
    pr0.xyzw = Material0(S0, pv2.xyxx.xy, float2(U_port_address0_0_x, U_port_address0_0_y)).xyzw.xyzw;
    pr0.w = (pr0.wwww * pv1.wwww).w;
    pr1.x = float4(pv3.xxxx >= pr0.wwww).x;
    clip((pr1.xxxx.x != 0) ? -1 : 1);
    pr0.w = (pr0.wwww * pv3.yyyy).w;
    pr0.xyz = (pr0.xyzx * pv1.xyzx + (-pv4.xyzx)).xyz;
    po0.xyz = (pv2.zzzz * pr0.xyzx + pv4.xyzx).xyz;
    po0.w = pr0.wwww.w;
    return po0;
}
