// Generated by shader_port.py from the game pair of shader key 0x01f007. Do not edit.
sampler S0 : register(s0);
float4 C0 : register(c0);
float4 C1 : register(c1);
float4 C2 : register(c2);
float4 C3 : register(c3);
float Level(float2 uv, float2 size, float bias, float last) {
    float2 dx = ddx(uv) * size, dy = ddy(uv) * size;
    return clamp(0.5 * log2(max(max(dot(dx, dx), dot(dy, dy)), 1e-30)) + bias, 0, last);
}
struct PS_INPUT {
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float4 t2 : TEXCOORD2;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float K0 = i.t0.x;
    float K1 = i.t0.y;
    float K2 = i.t0.z;
    float K3 = i.t0.w;
    float K4 = i.t1.x;
    float K5 = i.t1.y;
    float K6 = i.t1.z;
    float K7 = i.t1.w;
    float K8 = i.t2.x;
    float K9 = i.t2.y;
    float K10 = i.t2.z;
    float K11 = i.t2.w;
    float U_port_size0_0_x = 64;
    float U_port_size0_0_y = 64;
    float U_port_lod0_0_x = 0;
    float U_port_lod0_0_y = 2;
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vo2 = 0;
    float4 vo3 = 0;
    float4 vo4 = 0;
    float4 vr0 = 0;
    // ---- game vertex program: the part that needs per-draw constants ----
    vo1.x = K0;
    vo1.y = K1;
    vo1.z = K2;
    vo1.w = K3;
    vo2.x = K4;
    vo2.y = K5;
    vo2.z = K6;
    vo3.x = K7;
    vo3.y = K8;
    vo4.x = K9;
    vo4.y = K10;
    vo4.z = K11;
    // ---- game pixel program ----
    float4 pv1 = vo1;
    float4 pv2 = vo2;
    float4 pv3 = vo3;
    float4 pv4 = vo4;
    float4 po0 = 0;
    float4 po1 = 0;
    float4 pr0 = 0;
    float4 pr1 = 0;
    pr0.xyzw = tex2Dlod(S0, float4(pv2.xyxx.xy, 0, Level(pv2.xyxx.xy, float2(U_port_size0_0_x, U_port_size0_0_y), U_port_lod0_0_x, U_port_lod0_0_y))).xyzw.xyzw;
    pr0.w = (pr0.wwww * pv1.wwww).w;
    pr1.x = float4(pv3.xxxx >= pr0.wwww).x;
    clip((pr1.xxxx.x != 0) ? -1 : 1);
    pr0.w = (pr0.wwww * pv3.yyyy).w;
    pr0.xyz = (pr0.xyzx * pv1.xyzx + (-pv4.xyzx)).xyz;
    po0.xyz = (pv2.zzzz * pr0.xyzx + pv4.xyzx).xyz;
    po0.w = pr0.wwww.w;
    return po0;
}
