// Generated by shader_port.py from the game pair of shader key 0x01f012. Do not edit.
sampler S0 : register(s0);
sampler S1 : register(s1);
sampler S2 : register(s2);
float4 C0 : register(c0);
float4 C1 : register(c1);
float4 C2 : register(c2);
float4 C3 : register(c3);
float4 Material0(sampler s, float2 uv, float2 address) { return tex2D(s, uv); }
struct PS_INPUT {
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float A_COLOR0_x = i.t0.x;
    float A_COLOR0_y = i.t0.y;
    float A_COLOR0_z = i.t0.z;
    float A_COLOR0_w = i.t0.w;
    float A_TEXCOORD0_x = i.t1.x;
    float A_TEXCOORD0_y = i.t1.y;
    float B0 = i.t1.z;
    float B1 = i.t1.w;
    float U_g_uvOffset0_0_z = C1.x;
    float U_g_uvOffset0_0_w = C1.y;
    float U_g_uvOffset0_0_x = C0.z;
    float U_g_uvOffset0_0_y = C0.w;
    float U_g_ScreenToUV_0_x = B0;
    float U_g_ScreenToUV_0_y = B1;
    float U_g_commonParam_0_x = C0.x;
    float U_g_commonParam_0_y = C0.y;
    float2 ADDRESS = float2(0, 0);
    float4 A_COLOR0 = float4(A_COLOR0_x, A_COLOR0_y, A_COLOR0_z, A_COLOR0_w);
    float4 A_TEXCOORD0 = float4(A_TEXCOORD0_x, A_TEXCOORD0_y, 0, 1);
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vo2 = 0;
    float4 vo3 = 0;
    float4 vr0 = 0;
    // ---- game vertex program ----
    vo1.xyzw = A_COLOR0.xyzw.xyzw;
    vo2.xy = (A_TEXCOORD0.xyxx * float4(U_g_uvOffset0_0_z, U_g_uvOffset0_0_w, U_g_uvOffset0_0_z, U_g_uvOffset0_0_z) + float4(U_g_uvOffset0_0_x, U_g_uvOffset0_0_y, U_g_uvOffset0_0_x, U_g_uvOffset0_0_x)).xy;
    vo2.zw = float4(U_g_ScreenToUV_0_x, U_g_ScreenToUV_0_x, U_g_ScreenToUV_0_x, U_g_ScreenToUV_0_y).zw;
    vo3.xy = float4(U_g_commonParam_0_x, U_g_commonParam_0_y, U_g_commonParam_0_x, U_g_commonParam_0_x).xy;
    // ---- game pixel program ----
    float4 pv0 = float4(i.pixel.x + 0.5, i.pixel.y + 0.5, 0, 0);
    float4 pv1 = vo1;
    float4 pv2 = vo2;
    float4 pv3 = vo3;
    float4 po0 = 0;
    float4 po1 = 0;
    float4 pr0 = 0;
    float4 pr1 = 0;
    float4 pr2 = 0;
    float4 pr3 = 0;
    float4 pr4 = 0;
    pr0.xyzw = Material0(S0, pv2.xyxx.xy, ADDRESS).xyzw.xyzw;
    pr0.x = (pr0.wwww * pv1.wwww).x;
    pr0.y = float4(pv3.xxxx >= pr0.xxxx).y;
    clip((pr0.yyyy.x != 0) ? -1 : 1);
    pr0.yz = (pv0.xxyx * pv2.zzwz).yz;
    pr1.xyzw = tex2D(S2, pr0.yzyy.xy).xyzw.xyzw;
    pr2.xyzw = tex2D(S1, pr1.xxxx.xy).xyzw.xyzw;
    pr3.xyzw = tex2D(S1, pr1.yyyy.xy).xyzw.xyzw;
    pr1.xyzw = tex2D(S1, pr1.zzzz.xy).xyzw.xyzw;
    pr0.x = (pr0.xxxx * pv3.yyyy).x;
    po0.x = pr2.xxxx.x;
    po0.y = pr3.yyyy.y;
    po0.z = pr1.zzzz.z;
    po0.w = pr0.xxxx.w;
    return po0;
}
