// Generated by shader_port.py from the game pair of shader key 0x01f013. Do not edit.
float4 cMVP[4] : register(c4);
float4 cVP[4] : register(c8);
float4 cModel0[3] : register(c58);
struct VS_INPUT {
    float4 position : POSITION;
    float4 color : COLOR0;
    float2 uv0 : TEXCOORD0;
    float2 s1 : TEXCOORD1;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    float4 A_POSITION0 = float4(i.position.xyz, 1);
    o.position = float4(dot(A_POSITION0, cMVP[0]), dot(A_POSITION0, cMVP[1]), dot(A_POSITION0, cMVP[2]), dot(A_POSITION0, cMVP[3]));
    float4 A_COLOR0 = i.color;
    float4 A_TEXCOORD0 = float4(i.uv0, 0, 1);
    o.t0 = float4(A_COLOR0.x, A_COLOR0.y, A_COLOR0.z, A_COLOR0.w);
    o.t1 = float4(A_TEXCOORD0.x, A_TEXCOORD0.y, i.s1.x, i.s1.y);
    return o;
}
