// Generated by shader_port.py from the game pair of shader key 0x01f002. Do not edit.
sampler S0 : register(s0);
float4 C0 : register(c0);
float4 C1 : register(c1);
float4 C2 : register(c2);
float4 C3 : register(c3);
float Level(float2 uv, float2 size, float bias, float last) {
    float2 dx = ddx(uv) * size, dy = ddy(uv) * size;
    return clamp(0.5 * log2(max(max(dot(dx, dx), dot(dy, dy)), 1e-30)) + bias, 0, last);
}
struct PS_INPUT {
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float4 t2 : TEXCOORD2;
    float4 t3 : TEXCOORD3;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float K0 = i.t0.x;
    float K1 = i.t0.y;
    float A_COLOR0_x = i.t0.z;
    float A_COLOR0_y = i.t0.w;
    float A_COLOR0_z = i.t1.x;
    float A_TEXCOORD0_x = i.t1.y;
    float A_TEXCOORD0_y = i.t1.z;
    float U_g_ambientColor_0_x = i.t1.w;
    float U_g_ambientColor_0_y = i.t2.x;
    float U_g_ambientColor_0_z = i.t2.y;
    float U_g_fogColor_0_x = i.t2.z;
    float U_g_fogColor_0_y = i.t2.w;
    float U_g_fogColor_0_z = i.t3.x;
    float U_g_multColor_0_x = C0.z;
    float U_g_multColor_0_y = C0.w;
    float U_g_multColor_0_z = C1.x;
    float U_g_uvOffset0_0_z = C1.w;
    float U_g_uvOffset0_0_w = C2.x;
    float U_g_uvOffset0_0_x = C1.y;
    float U_g_uvOffset0_0_y = C1.z;
    float U_port_size0_0_x = 64;
    float U_port_size0_0_y = 64;
    float U_port_lod0_0_x = -2;
    float U_port_lod0_0_y = 2;
    float U_g_commonParam_0_x = C0.x;
    float U_g_commonParam_0_y = C0.y;
    float4 A_COLOR0 = float4(A_COLOR0_x, A_COLOR0_y, A_COLOR0_z, 0);
    float4 A_TEXCOORD0 = float4(A_TEXCOORD0_x, A_TEXCOORD0_y, 0, 1);
    float4 vo0 = 0;
    float4 vo1 = 0;
    float4 vo2 = 0;
    float4 vr0 = 0;
    // ---- game vertex program: the part that needs per-draw constants ----
    vr0.yzw = (A_COLOR0.xxyz * float4(0, U_g_multColor_0_x, U_g_multColor_0_y, U_g_multColor_0_z)).yzw;
    vo1.xyz = (vr0.yzwy * float4(U_g_ambientColor_0_x, U_g_ambientColor_0_y, U_g_ambientColor_0_z, 0)).xyz;
    vo2.xy = (A_TEXCOORD0.xyxx * float4(U_g_uvOffset0_0_z, U_g_uvOffset0_0_w, 0, 0) + float4(U_g_uvOffset0_0_x, U_g_uvOffset0_0_y, 0, 0)).xy;
    vo1.w = K0;
    vo2.z = K1;
    // ---- game pixel program ----
    float4 pv1 = vo1;
    float4 pv2 = vo2;
    float4 po0 = 0;
    float4 po1 = 0;
    float4 pr0 = 0;
    float4 pr1 = 0;
    pr0.xyzw = tex2Dlod(S0, float4(pv2.xyxx.xy, 0, Level(pv2.xyxx.xy, float2(U_port_size0_0_x, U_port_size0_0_y), U_port_lod0_0_x, U_port_lod0_0_y))).xyzw.xyzw;
    pr0.w = (pr0.wwww * pv1.wwww).w;
    pr1.x = float4(float4(U_g_commonParam_0_x, 0, 0, 0) >= pr0.wwww).x;
    clip((pr1.xxxx.x != 0) ? -1 : 1);
    pr0.w = (pr0.wwww * float4(0, 0, 0, U_g_commonParam_0_y)).w;
    pr0.xyz = (pr0.xyzx * pv1.xyzx + (-float4(U_g_fogColor_0_x, U_g_fogColor_0_y, U_g_fogColor_0_z, 0))).xyz;
    po0.xyz = (pv2.zzzz * pr0.xyzx + float4(U_g_fogColor_0_x, U_g_fogColor_0_y, U_g_fogColor_0_z, 0)).xyz;
    po0.w = pr0.wwww.w;
    return po0;
}
