// Generated by shader_port.py from the game pair of shader key 0x01f004. Do not edit.
float4 cMVP[4] : register(c4);
float4 cVP[4] : register(c8);
float4 cModel0[3] : register(c58);
struct VS_INPUT {
    float4 position : POSITION;
    float3 normal : NORMAL;
    float4 color : COLOR0;
    float2 uv0 : TEXCOORD0;
    float2 s1 : TEXCOORD1;
    float2 s2 : TEXCOORD2;
    float2 s3 : TEXCOORD3;
    float2 s4 : TEXCOORD4;
    float2 s5 : TEXCOORD5;
    float2 s6 : TEXCOORD6;
    float2 s7 : TEXCOORD7;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 t0 : TEXCOORD0;
    float4 t1 : TEXCOORD1;
    float4 t2 : TEXCOORD2;
    float4 t3 : TEXCOORD3;
    float4 t4 : TEXCOORD4;
    float4 t5 : TEXCOORD5;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    float4 A_POSITION0 = float4(i.position.xyz, 1);
    o.position = float4(dot(A_POSITION0, cMVP[0]), dot(A_POSITION0, cMVP[1]), dot(A_POSITION0, cMVP[2]), dot(A_POSITION0, cMVP[3]));
    float4 A_NORMAL0 = float4(i.normal, 0);
    float4 A_COLOR0 = i.color;
    float4 A_TEXCOORD0 = float4(i.uv0, 0, 1);
    float4 M_g_matWorldViewProj[4];
    M_g_matWorldViewProj[0] = float4(cMVP[0].x, cMVP[1].x, cMVP[2].x, cMVP[3].x);
    M_g_matWorldViewProj[1] = float4(cMVP[0].y, cMVP[1].y, cMVP[2].y, cMVP[3].y);
    M_g_matWorldViewProj[2] = float4(cMVP[0].z, cMVP[1].z, cMVP[2].z, cMVP[3].z);
    M_g_matWorldViewProj[3] = float4(cMVP[0].w, cMVP[1].w, cMVP[2].w, cMVP[3].w);
    o.t0 = float4(A_COLOR0.x, A_COLOR0.y, A_COLOR0.z, A_COLOR0.w);
    o.t1 = float4(A_NORMAL0.x, A_NORMAL0.y, A_NORMAL0.z, A_TEXCOORD0.x);
    o.t2 = float4(A_TEXCOORD0.y, A_POSITION0.x * M_g_matWorldViewProj[0].w + A_POSITION0.y * M_g_matWorldViewProj[1].w + A_POSITION0.z * M_g_matWorldViewProj[2].w + A_POSITION0.w * M_g_matWorldViewProj[3].w, i.s1.x, i.s1.y);
    o.t3 = float4(i.s2.x, i.s2.y, i.s3.x, i.s3.y);
    o.t4 = float4(i.s4.x, i.s4.y, i.s5.x, i.s5.y);
    o.t5 = float4(i.s6.x, i.s6.y, i.s7.x, i.s7.y);
    return o;
}
