-- Generated by storm_import.py from the game files. Decoded values only;
-- do not tune these numbers by eye.
return {["format"]=1,["name"]="2itcspl1_x",["skills"]={["2itcspl1_e_all"]={["id"]="2itcspl1_e_all",["type"]="SKILL_TYPE_EFFECT",["hit"]=nil,["files"]={"data/effect/2efb_tkt.xfbin"},["actions"]={},["other"]={}}},["effects"]={},["spatialRecords"]={},["animations"]={},["resources"]={},["models"]={},["textures"]={},["unsupported"]={},["source"]="data/skill/2itcspl1_x.xfbin",["borrowed"]={},["files"]={"data/effect/2efb_tkt.xfbin"},["externalFiles"]={}}
