-- Generated by storm_import.py from the game files. Decoded values only;
-- do not tune these numbers by eye.
return {["format"]=1,["name"]="2knxspl1_x",["skills"]={["1inospl1_e_all"]={["id"]="1inospl1_e_all",["type"]="SKILL_TYPE_EFFECT",["hit"]=nil,["files"]={"data/spc/1inospl1.xfbin"},["actions"]={},["other"]={}}},["effects"]={},["spatialRecords"]={},["animations"]={},["resources"]={},["models"]={},["textures"]={},["unsupported"]={},["source"]="data/skill/2knxspl1_x.xfbin",["borrowed"]={},["files"]={"data/spc/1inospl1.xfbin"},["externalFiles"]={}}
