-- Generated by storm_import.py from the game files. Decoded values only;
-- do not tune these numbers by eye.
return {["format"]=1,["name"]="2sszspl1_x",["skills"]={["2sszspl1_e_all"]={["id"]="2sszspl1_e_all",["type"]="SKILL_TYPE_EFFECT",["hit"]=nil,["files"]={"data/effect/2efb_ssn.xfbin"},["actions"]={},["other"]={}}},["effects"]={},["spatialRecords"]={},["animations"]={},["resources"]={},["models"]={},["textures"]={},["unsupported"]={},["source"]="data/skill/2sszspl1_x.xfbin",["borrowed"]={},["files"]={"data/effect/2efb_ssn.xfbin"},["externalFiles"]={}}
