-- Generated by storm_import.py from the game files. Decoded values only;
-- do not tune these numbers by eye.
return {["format"]=1,["name"]="3ygreff1",["skills"]={},["effects"]={},["spatialRecords"]={},["animations"]={},["resources"]={},["models"]={},["textures"]={},["unsupported"]={},["source"]="data/skill/3ygreff1.xfbin",["borrowed"]={},["files"]={},["externalFiles"]={}}
