// Generated by build_storm_fx_shaders.py. Generic Storm effect pixel shader, FILM = 1.
sampler TexBase : register(s0);
sampler TexFilm0 : register(s1);
sampler TexFilm1 : register(s2);
float4 Atlas : register(c0);          // g_uvOffset0
float4 TintThreshold : register(c1);  // g_multColor.rgb * g_ambientColor.rgb, g_commonParam.x
float4 FilmOffset : register(c2);     // g_uvOffsetScreen
float4 FogAlpha : register(c3);       // g_fogColor.rgb, g_commonParam.y
struct PS_INPUT {
    float4 uvw : TEXCOORD0;
    float4 filmScale : TEXCOORD1;
    float4 filmFog : TEXCOORD2;
    float4 screen : TEXCOORD3;
    float4 color : TEXCOORD4;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    // Base-texture addressing the VTF cannot express. Per axis: 0 = as the VTF
    // says (wrap, or clamp for the *_c variants), < 0 = mirror, > 0 = border
    // (0,0,0,0) with the value being the texture size. Both run on a clamped
    // VTF and equal D3D bilinear filtering at mip 0, the only mip the game's
    // effect samplers reach (LOD bias -16).
    float2 uv = i.uvw.xy * Atlas.zw + Atlas.xy;
    float2 address = i.screen.zw;
    float2 mirrored = 1 - abs(frac(uv * 0.5) * 2 - 1);
    uv = address < 0 ? mirrored : uv;
    float4 tex = tex2D(TexBase, uv);
    float2 inside = saturate(uv * address + 0.5) * saturate((1 - uv) * address + 0.5);
    inside = address > 0 ? inside : 1;
    tex *= inside.x * inside.y;
    float alpha = tex.a * i.color.a;
    clip(TintThreshold.w >= alpha ? -1 : 1);
    float3 rgb = tex.rgb * (i.color.rgb * TintThreshold.rgb);
    // D3D9 vPos is the integer pixel; the game's SV_Position is its centre.
    float2 screenUV = (i.pixel + 0.5) * i.screen.xy;
    float2 uv0 = screenUV * float2(i.filmScale.x, -i.filmScale.y) + FilmOffset.xy * i.filmScale.xy;
    uv0.y = 1 - uv0.y;
    float4 film0 = tex2D(TexFilm0, uv0);
    rgb += (film0.a * i.filmFog.x) * (film0.rgb - rgb);
    float fog = 1 + i.uvw.w * (saturate((i.filmFog.w - i.uvw.z) / (i.filmFog.w - i.filmFog.z)) - 1);
    rgb = FogAlpha.rgb + fog * (rgb - FogAlpha.rgb);
    return float4(rgb, alpha * FogAlpha.a);
}
