// Generated by build_storm_fx_shaders.py. Storm effect pixel shader, falloff variant.
sampler TexBase : register(s0);
sampler TexFalloff : register(s1);
float4 Atlas : register(c0);          // g_uvOffset0
float4 TintThreshold : register(c1);  // g_multColor.rgb * g_ambientColor.rgb, g_commonParam.x
float4 ViewAxis : register(c2);       // view z axis in model space, g_uvOffset2.x
float4 FogAlpha : register(c3);       // g_fogColor.rgb, g_commonParam.y
struct PS_INPUT {
    float4 uvw : TEXCOORD0;
    float4 normal : TEXCOORD1;
    float4 filmFog : TEXCOORD2;
    float4 screen : TEXCOORD3;
    float4 color : TEXCOORD4;
};
float4 main(PS_INPUT i) : COLOR {
    float2 uv = i.uvw.xy * Atlas.zw + Atlas.xy;
    float2 address = i.screen.zw;
    float2 mirrored = 1 - abs(frac(uv * 0.5) * 2 - 1);
    uv = address < 0 ? mirrored : uv;
    float4 tex = tex2D(TexBase, uv);
    float2 inside = saturate(uv * address + 0.5) * saturate((1 - uv) * address + 0.5);
    inside = address > 0 ? inside : 1;
    tex *= inside.x * inside.y;
    float3 n = i.normal.xyz;
    float facing = min(abs(dot(n, ViewAxis.xyz) * rsqrt(dot(n, n))), 1);
    float4 falloff = tex2D(TexFalloff, float2(facing, ViewAxis.w));
    float alpha = tex.a * i.color.a * falloff.g;
    clip(TintThreshold.w >= alpha ? -1 : 1);
    float3 rgb = tex.rgb * (i.color.rgb * TintThreshold.rgb);
    float fog = 1 + i.uvw.w * (saturate((i.filmFog.w - i.uvw.z) / (i.filmFog.w - i.filmFog.z)) - 1);
    rgb = FogAlpha.rgb + fog * (rgb - FogAlpha.rgb);
    return float4(rgb, alpha * FogAlpha.a);
}
