// Generated by build_storm_fx_shaders.py. Storm effect vertex shader, falloff variant.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float3 normal : NORMAL;
    float4 color : COLOR0;
    float2 uv : TEXCOORD0;
    float2 fogRange : TEXCOORD4;
    float2 fogStrength : TEXCOORD5;
    float2 address : TEXCOORD7;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uvw : TEXCOORD0;        // uv, clip w, fog strength
    float4 normal : TEXCOORD1;     // model-space normal
    float4 filmFog : TEXCOORD2;    // 0, 0, fog start, fog end
    float4 screen : TEXCOORD3;     // 0, 0, base-texture address codes
    float4 color : TEXCOORD4;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uvw = float4(i.uv, o.position.w, i.fogStrength.x);
    o.normal = float4(i.normal, 0);
    o.filmFog = float4(0, 0, i.fogRange);
    o.screen = float4(0, 0, i.address);
    o.color = i.color;
    return o;
}
