// Generated by build_storm_fx_shaders.py. Storm effect pixel shader, refraction variant.
sampler TexNormal : register(s0);
sampler TexScene : register(s1);
float4 Offset0 : register(c0);      // g_uvOffset0
float4 Offset1 : register(c1);      // g_uvOffset1.xy, g_commonParam.y * g_uvOffset1.z, 0
float4 ScaleNormal : register(c2);  // g_uvScaleNormal
float4 ScaleAlpha : register(c3);   // g_uvScaleAlpha.xy, 0, 0
struct PS_INPUT {
    float4 uv : TEXCOORD0;
    float4 screen : TEXCOORD1;
    float4 color : TEXCOORD2;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float2 uvA = i.uv.xy * ScaleNormal.xy + Offset0.xy * float2(1, -1);
    float2 uvB = i.uv.yx * ScaleNormal.wz + float2(-Offset1.y, Offset1.x);
    float2 uvC = i.uv.zw * ScaleAlpha.xy + Offset0.zw * float2(1, -1);
    float2 bend = tex2D(TexNormal, uvA).xy + tex2D(TexNormal, uvB).xy - 1;
    bend *= Offset1.z * i.color.r;
    bend *= tex2D(TexNormal, uvC).a;
    bend += bend;
    float2 screenUV = (i.pixel + 0.5) * i.screen.xy + float2(bend.x, -bend.y);
    return float4(tex2D(TexScene, screenUV).rgb, i.color.a);
}
