// Generated by build_storm_fx_shaders.py. Storm stage tone control.
sampler Scene : register(s0);
float4 Shift : register(c0);    // paramR.x, paramG.y, paramB.z, lparam.w
float4 Low : register(c1);      // lparam.rgb
float4 High : register(c2);     // hparam.rgb
float4 Texel : register(c3);    // 1/width, 1/height
float4 main(float2 pixel : VPOS) : COLOR {
    float3 c = tex2D(Scene, (pixel + 0.5) * Texel.xy).rgb;
    c += (1 - (c - 0.5) * 2) * Shift.xyz * 0.666667;
    float luma = dot(c, float3(0.298912, 0.586611, 0.114478));
    float dark = min(saturate(0.35 - luma) * 5.714286, 1);
    float bright = min(saturate(luma - 0.65) * 5.714286, 1);
    float3 low = c + dark * Low.rgb;
    c = low + bright * (c + High.rgb - low);
    float4 p = c.g < c.b ? float4(c.b, c.g, -1, 0.666667) : float4(c.g, c.b, 0, -0.333333);
    float4 q = c.r < p.x ? float4(p.x, p.y, p.w, c.r) : float4(c.r, p.y, p.z, p.x);
    float chroma = q.x - min(q.w, q.y);
    float3 hue = -1;
    if (chroma != 0) {
        float h = abs((q.w - q.y) / (chroma * 6) + q.z);
        hue = saturate(abs(frac(h + float3(1, 0.666667, 0.333333)) * 6 - 3) - 1) - 1;
    }
    float saturation = q.x != 0 ? max(chroma / q.x + Shift.w, 0) : 0;
    return float4((saturation * hue + 1) * q.x, 1);
}
