// Generated by build_storm_fx_shaders.py. Storm effect vertex shader, refraction variant.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float4 color : COLOR0;
    float2 uv0 : TEXCOORD0;
    float2 uv1 : TEXCOORD1;
    float2 screen : TEXCOORD6;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uv : TEXCOORD0;
    float4 screen : TEXCOORD1;
    float4 color : TEXCOORD2;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uv = float4(i.uv0, i.uv1);
    o.screen = float4(i.screen, 0, 0);
    o.color = i.color;
    return o;
}
