// Generated by build_storm_fx_shaders.py. Generic Storm effect vertex shader.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float4 color : COLOR0;
    float2 uv : TEXCOORD0;
    float2 filmScaleXY : TEXCOORD1;
    float2 filmScaleZW : TEXCOORD2;
    float2 filmWeight : TEXCOORD3;
    float2 fogRange : TEXCOORD4;
    float2 fogStrength : TEXCOORD5;
    float2 screen : TEXCOORD6;
    float2 address : TEXCOORD7;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uvw : TEXCOORD0;        // uv, clip w, fog strength
    float4 filmScale : TEXCOORD1;  // g_uvScaleScreen
    float4 filmFog : TEXCOORD2;    // g_uvOffset3.xy, fog start, fog end
    float4 screen : TEXCOORD3;     // 1/width, 1/height, base-texture address codes
    float4 color : TEXCOORD4;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    // Source's cModelViewProj takes a row vector on the left.
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uvw = float4(i.uv, o.position.w, i.fogStrength.x);
    o.filmScale = float4(i.filmScaleXY, i.filmScaleZW);
    o.filmFog = float4(i.filmWeight, i.fogRange);
    o.screen = float4(i.screen, i.address);
    o.color = i.color;
    return o;
}
