//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer perMaterialBuffer
// {
//
//   float4 g_commonParam;              // Offset:    0 Size:    16
//   float4 g_fogColor;                 // Offset:   16 Size:    16
//   float4 g_fogParam;                 // Offset:   32 Size:    16 [unused]
//   float4 g_ambientColor;             // Offset:   48 Size:    16 [unused]
//   float4 g_lightDirection;           // Offset:   64 Size:    16 [unused]
//   float3 g_pointLightPos0;           // Offset:   80 Size:    12 [unused]
//   float3 g_pointLightColor0;         // Offset:   96 Size:    12 [unused]
//   float4 g_pointLightParam0;         // Offset:  112 Size:    16 [unused]
//   float3 g_pointLightPos1;           // Offset:  128 Size:    12 [unused]
//   float3 g_pointLightColor1;         // Offset:  144 Size:    12 [unused]
//   float4 g_pointLightParam1;         // Offset:  160 Size:    16 [unused]
//   float3 g_pointLightPos2;           // Offset:  176 Size:    12 [unused]
//   float3 g_pointLightColor2;         // Offset:  192 Size:    12 [unused]
//   float4 g_pointLightParam2;         // Offset:  208 Size:    16 [unused]
//   float3 g_pointLightPos3;           // Offset:  224 Size:    12 [unused]
//   float3 g_pointLightColor3;         // Offset:  240 Size:    12 [unused]
//   float4 g_pointLightParam3;         // Offset:  256 Size:    16 [unused]
//   row_major float4x4 g_matWorldViewProj;// Offset:  272 Size:    64 [unused]
//   float4 g_uvOffset0;                // Offset:  336 Size:    16 [unused]
//   float4 g_uvOffset1;                // Offset:  352 Size:    16 [unused]
//   float4 g_blendRate;                // Offset:  368 Size:    16 [unused]
//   float4 g_blendType;                // Offset:  384 Size:    16 [unused]
//   float4 g_multColor;                // Offset:  400 Size:    16 [unused]
//   row_major float4x4 g_matWorld;     // Offset:  416 Size:    64 [unused]
//   row_major float4x4 g_matWorldInvTrans;// Offset:  480 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj0;// Offset:  544 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj1;// Offset:  608 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj2;// Offset:  672 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj3;// Offset:  736 Size:    64 [unused]
//   float4 g_shadowParam;              // Offset:  800 Size:    16
//   float4 g_shadowColor;              // Offset:  816 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_sampler0                        sampler      NA          NA    0        1
// g_samplerLightmap                 sampler      NA          NA    1        1
// g_samplerShadow                   sampler      NA          NA    2        1
// g_texture0                        texture  float4          2d    0        1
// g_textureLightmap                 texture  float4          2d    1        1
// g_textureShadow                   texture  float4          2d    2        1
// perMaterialBuffer                 cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
// TEXCOORD                 1   x           3     NONE   float   x   
// TEXCOORD                 5    y          3     NONE   float    y  
// TEXCOORD                 2   xyzw        4     NONE   float   xyzw
// TEXCOORD                 3   xyzw        5     NONE   float   xyzw
// TEXCOORD                 4   xyzw        6     NONE   float   xyzw
// TEXCOORD                 9   xyzw        7     NONE   float   xyzw
// COLOR                    1   xyzw        8     NONE   float      w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer cb0[52], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.x
dcl_input_ps linear v3.y
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyzw
dcl_input_ps linear v7.xyzw
dcl_input_ps linear v8.w
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 8
sample r0.xyzw, v2.xyxx, t0.xyzw, s0
sample r1.xyzw, v2.zwzz, t1.xyzw, s1
mul r0.xyz, r0.xyzx, r1.xyzx
mul r0.xyzw, r0.xyzw, v1.xyzw
lt r1.x, cb0[50].z, v8.w
div r1.yzw, v7.xxyz, v7.wwww
sample r2.xyzw, r1.yzyy, t2.xyzw, s2
div r3.xyz, v6.xyzx, v6.wwww
sample r4.xyzw, r3.xyxx, t2.xyzw, s2
div r3.xyw, v5.xyxz, v5.wwww
sample r5.xyzw, r3.xyxx, t2.xyzw, s2
div r6.xyz, v4.xyzx, v4.wwww
sample r7.xyzw, r6.xyxx, t2.xyzw, s2
if_nz r1.x
  ge r1.x, r2.x, r1.w
  ne r1.y, r2.x, l(0.000000)
  and r1.x, r1.y, r1.x
  mad r1.y, -r2.x, r2.x, r2.y
  add r1.z, -r1.w, r2.x
  mad_sat r2.z, |r1.z|, l(3.000000), l(-0.300000)
  add r1.y, r1.y, l(-0.000020)
  mad r1.y, r2.z, r1.y, l(0.000020)
  mad r1.z, r1.z, r1.z, r1.y
  max r1.z, r1.z, l(0.000000)
  div r1.y, r1.y, r1.z
  add r1.y, r1.y, l(-0.000100)
  mul_sat r1.y, r1.y, l(1.000100)
  movc r1.x, r1.x, l(1.000000), r1.y
else 
  lt r1.y, cb0[50].y, v8.w
  if_nz r1.y
    ge r1.y, r2.x, r1.w
    ne r1.z, r2.x, l(0.000000)
    and r1.y, r1.z, r1.y
    mad r1.z, -r2.x, r2.x, r2.y
    add r1.w, -r1.w, r2.x
    mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
    add r1.z, r1.z, l(-0.000020)
    mad r1.z, r2.x, r1.z, l(0.000020)
    mad r1.w, r1.w, r1.w, r1.z
    max r1.w, r1.w, l(0.000000)
    div r1.z, r1.z, r1.w
    add r1.z, r1.z, l(-0.000100)
    mul_sat r1.z, r1.z, l(1.000100)
    movc r1.y, r1.y, l(1.000000), r1.z
    ge r1.z, r4.x, r3.z
    ne r1.w, r4.x, l(0.000000)
    and r1.z, r1.w, r1.z
    mad r1.w, -r4.x, r4.x, r4.y
    add r2.x, -r3.z, r4.x
    mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
    add r1.w, r1.w, l(-0.000020)
    mad r1.w, r2.y, r1.w, l(0.000020)
    mad r2.x, r2.x, r2.x, r1.w
    max r2.x, r2.x, l(0.000000)
    div r1.w, r1.w, r2.x
    add r1.w, r1.w, l(-0.000100)
    mul_sat r1.w, r1.w, l(1.000100)
    movc r1.z, r1.z, l(1.000000), r1.w
    add r1.w, cb0[50].z, l(-200.000000)
    add r1.w, -r1.w, v8.w
    mul_sat r1.w, r1.w, l(0.005000)
    add r1.y, -r1.z, r1.y
    mad r1.x, r1.w, r1.y, r1.z
  else 
    lt r1.y, cb0[50].x, v8.w
    if_nz r1.y
      ge r1.y, r4.x, r3.z
      ne r1.z, r4.x, l(0.000000)
      and r1.y, r1.z, r1.y
      mad r1.z, -r4.x, r4.x, r4.y
      add r1.w, -r3.z, r4.x
      mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
      add r1.z, r1.z, l(-0.000020)
      mad r1.z, r2.x, r1.z, l(0.000020)
      mad r1.w, r1.w, r1.w, r1.z
      max r1.w, r1.w, l(0.000000)
      div r1.z, r1.z, r1.w
      add r1.z, r1.z, l(-0.000100)
      mul_sat r1.z, r1.z, l(1.000100)
      movc r1.y, r1.y, l(1.000000), r1.z
      ge r1.z, r5.x, r3.w
      ne r1.w, r5.x, l(0.000000)
      and r1.z, r1.w, r1.z
      mad r1.w, -r5.x, r5.x, r5.y
      add r2.x, -r3.w, r5.x
      mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
      add r1.w, r1.w, l(-0.000020)
      mad r1.w, r2.y, r1.w, l(0.000020)
      mad r2.x, r2.x, r2.x, r1.w
      max r2.x, r2.x, l(0.000000)
      div r1.w, r1.w, r2.x
      add r1.w, r1.w, l(-0.000100)
      mul_sat r1.w, r1.w, l(1.000100)
      movc r1.z, r1.z, l(1.000000), r1.w
      add r1.w, cb0[50].y, l(-200.000000)
      add r1.w, -r1.w, v8.w
      mul_sat r1.w, r1.w, l(0.005000)
      add r1.y, -r1.z, r1.y
      mad r1.x, r1.w, r1.y, r1.z
    else 
      ge r1.y, r5.x, r3.w
      ne r1.z, r5.x, l(0.000000)
      and r1.y, r1.z, r1.y
      mad r1.z, -r5.x, r5.x, r5.y
      add r1.w, -r3.w, r5.x
      mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
      add r1.z, r1.z, l(-0.000020)
      mad r1.z, r2.x, r1.z, l(0.000020)
      mad r1.w, r1.w, r1.w, r1.z
      max r1.w, r1.w, l(0.000000)
      div r1.z, r1.z, r1.w
      add r1.z, r1.z, l(-0.000100)
      mul_sat r1.z, r1.z, l(1.000100)
      movc r1.y, r1.y, l(1.000000), r1.z
      ge r1.z, r7.x, r6.z
      ne r1.w, r7.x, l(0.000000)
      and r1.z, r1.w, r1.z
      mad r1.w, -r7.x, r7.x, r7.y
      add r2.x, -r6.z, r7.x
      mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
      add r1.w, r1.w, l(-0.000020)
      mad r1.w, r2.y, r1.w, l(0.000020)
      mad r2.x, r2.x, r2.x, r1.w
      max r2.x, r2.x, l(0.000000)
      div r1.w, r1.w, r2.x
      add r1.w, r1.w, l(-0.000100)
      mul_sat r1.w, r1.w, l(1.000100)
      movc r1.z, r1.z, l(1.000000), r1.w
      add r1.w, cb0[50].x, l(-200.000000)
      add r1.w, -r1.w, v8.w
      mul_sat r1.w, r1.w, l(0.005000)
      add r1.y, -r1.z, r1.y
      mad r1.x, r1.w, r1.y, r1.z
    endif 
  endif 
endif 
ge r1.y, cb0[0].x, r0.w
discard_nz r1.y
add r1.y, -v8.w, cb0[50].w
mul_sat r1.y, r1.y, l(0.002000)
add r1.x, r1.x, l(-1.000000)
mad r1.x, r1.y, r1.x, l(1.000000)
mad_sat r1.y, v3.y, l(3.000000), cb0[51].w
mul r1.x, r1.y, r1.x
add r1.yzw, -cb0[51].xxyz, l(0.000000, 1.000000, 1.000000, 1.000000)
mad r1.xyz, r1.xxxx, r1.yzwy, cb0[51].xyzx
mul r0.w, r0.w, cb0[0].y
mad r0.xyz, r0.xyzx, r1.xyzx, -cb0[1].xyzx
mad o0.xyz, v3.xxxx, r0.xyzx, cb0[1].xyzx
mov o0.w, r0.w
mov o1.xy, cb0[0].wzww
mov o1.z, l(0.990000)
mov o1.w, r0.w
ret 
// Approximately 155 instruction slots used
 