//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer perMaterialBuffer
// {
//
//   float4 g_commonParam;              // Offset:    0 Size:    16 [unused]
//   float4 g_outlineID;                // Offset:   16 Size:    16 [unused]
//   float4 g_olIdParam;                // Offset:   32 Size:    16 [unused]
//   float4 g_fogColor;                 // Offset:   48 Size:    16 [unused]
//   float4 g_fogParam;                 // Offset:   64 Size:    16 [unused]
//   float4 g_ambientColor;             // Offset:   80 Size:    16 [unused]
//   float4 g_lightColor;               // Offset:   96 Size:    16 [unused]
//   float4 g_lightDirection;           // Offset:  112 Size:    16 [unused]
//   float3 g_pointLightPos0;           // Offset:  128 Size:    12 [unused]
//   float3 g_pointLightColor0;         // Offset:  144 Size:    12 [unused]
//   float4 g_pointLightParam0;         // Offset:  160 Size:    16 [unused]
//   row_major float4x4 g_matWorldViewProj;// Offset:  176 Size:    64 [unused]
//   float4 g_uvOffset0;                // Offset:  240 Size:    16 [unused]
//   float4 g_uvOffset1;                // Offset:  256 Size:    16 [unused]
//   float4 g_blendRate;                // Offset:  272 Size:    16 [unused]
//   float4 g_blendType;                // Offset:  288 Size:    16 [unused]
//   float4 g_celShadeParam;            // Offset:  304 Size:    16 [unused]
//   float4 g_toneOffsetParam;          // Offset:  320 Size:    16 [unused]
//   float4 g_shadeColor;               // Offset:  336 Size:    16
//   row_major float4x4 g_matWorld;     // Offset:  352 Size:    64 [unused]
//   row_major float4x4 g_matWorldInvTrans;// Offset:  416 Size:    64 [unused]
//   float4 g_uvOffset2;                // Offset:  480 Size:    16 [unused]
//   float4 g_ScreenToUV;               // Offset:  496 Size:    16 [unused]
//   float4 g_uvOffset3;                // Offset:  512 Size:    16 [unused]
//   float4 g_uvOffsetScreen;           // Offset:  528 Size:    16 [unused]
//   float4 g_uvScaleScreen;            // Offset:  544 Size:    16 [unused]
//   float4 g_screenProjParam;          // Offset:  560 Size:    16 [unused]
//   float4 g_cparaColor1;              // Offset:  576 Size:    16
//   float4 g_cparaColor2;              // Offset:  592 Size:    16
//   float4 g_cparaParam;               // Offset:  608 Size:    16
//   float4 g_stageColor;               // Offset:  624 Size:    16
//   float4 g_useStColor;               // Offset:  640 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_sampler0                        sampler      NA          NA    0        1
// g_sampler1                        sampler      NA          NA    1        1
// g_samplerScreen0                  sampler      NA          NA    2        1
// g_samplerScreen1                  sampler      NA          NA    3        1
// g_samplerTone                     sampler      NA          NA    4        1
// g_texture0                        texture  float4          2d    0        1
// g_texture1                        texture  float4          2d    1        1
// g_textureScreen0                  texture  float4          2d    2        1
// g_textureScreen1                  texture  float4          2d    3        1
// g_textureTone                     texture  float4          2d    4        1
// perMaterialBuffer                 cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyz         2     NONE   float   xyz 
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// COLOR                    0   xyzw        4     NONE   float   xyzw
// COLOR                    1   xyzw        5     NONE   float   xyzw
// TEXCOORD                 3   xyz         6     NONE   float   xyz 
// TEXCOORD                 4   xyz         7     NONE   float   xyz 
// TEXCOORD                 5   xyz         8     NONE   float   xyz 
// TEXCOORD                 6   xyzw        9     NONE   float   xyzw
// TEXCOORD                 7   xyzw       10     NONE   float   xyzw
// TEXCOORD                 8   xyzw       11     NONE   float   xyzw
// TEXCOORD                 9   xyzw       12     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xyzw        2   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer cb0[41], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xyz
dcl_input_ps linear v8.xyz
dcl_input_ps linear v9.xyzw
dcl_input_ps linear v10.xyzw
dcl_input_ps linear v11.xyzw
dcl_input_ps linear v12.xyzw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 7
sample r0.xyzw, v1.xyxx, t0.xyzw, s0
sample r1.xyzw, v1.zwzz, t1.xyzw, s1
mul r2.xy, r1.wwww, v6.yxyy
add r3.xyz, r0.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
mad r3.xyz, v6.xxxx, r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul_sat r3.xyz, r1.xyzx, r3.xyzx
mad_sat r3.w, r0.w, v6.x, r2.x
add r4.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
mad r4.xyzw, v6.xxxx, r4.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
add r5.xyzw, r1.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
mad r5.xyzw, v6.yyyy, r5.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
mul_sat r4.xyzw, r4.xyzw, r5.xyzw
lt r2.xzw, l(2.500000, 0.000000, 1.500000, 0.500000), v6.zzzz
mov_sat r5.x, v6.x
add r5.y, -r5.x, l(1.000000)
mul r6.xyzw, r1.xyzw, r5.yyyy
mad r5.xyzw, r0.xyzw, r5.xxxx, r6.xyzw
mad r1.w, -r1.w, v6.x, l(1.000000)
mul r1.xyz, r1.xyzx, r2.yyyy
mad r0.xyz, r0.xyzx, r1.wwww, r1.xyzx
movc r0.xyzw, r2.wwww, r5.xyzw, r0.xyzw
movc r0.xyzw, r2.zzzz, r4.xyzw, r0.xyzw
movc r0.xyzw, r2.xxxx, r3.xyzw, r0.xyzw
ge r1.x, v4.x, r0.w
discard_nz r1.x
dp3 r1.x, v8.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
dp3 r1.y, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
max r1.z, r0.z, r0.y
max r1.z, r0.x, r1.z
min r1.w, r0.z, r0.y
min r1.w, r0.x, r1.w
ne r2.x, l(0.000000, 0.000000, 0.000000, 0.000000), r1.z
add r1.w, -r1.w, r1.z
div r1.z, r1.w, r1.z
and r1.z, r1.z, r2.x
max r1.w, v8.z, v8.y
max r1.w, r1.w, v8.x
min r2.x, v8.z, v8.y
min r2.x, r2.x, v8.x
ne r2.y, l(0.000000, 0.000000, 0.000000, 0.000000), r1.w
add r2.x, r1.w, -r2.x
div r1.w, r2.x, r1.w
and r1.w, r1.w, r2.y
max r1.x, r1.w, r1.x
max r1.x, r1.x, r1.z
sample r2.xyzw, v2.xyxx, t4.xyzw, s4
sample r3.xyzw, v3.xyxx, t4.xyzw, s4
mul r3.xyz, r3.xyzx, v3.zzzz
mul r4.xyz, r3.xyzx, v9.wwww
mad r2.xyz, r3.xyzx, v9.wwww, r2.xyzx
mul r2.xyz, r2.xyzx, l(10000.000000, 10000.000000, 10000.000000, 0.000000)
round_ne r2.xyz, r2.xyzx
mov r3.x, l(0.000100)
mov r3.yz, v7.yyzy
mul r2.yzw, r2.xxyz, r3.xxyz
lt r1.z, r2.x, l(5000.000000)
ne r1.y, r1.y, l(0.000000)
and r1.y, r1.y, r1.z
mov r5.x, v7.x
mov r5.yz, l(0,0.000100,0.000100,0)
mad r3.yzw, r2.yyzw, r5.xxyz, v8.xxyz
mad_sat r3.yzw, v9.xxyz, r4.xxyz, r3.yyzw
mul r4.xyz, r0.xyzx, r3.yzwy
add r5.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r5.xyz, r5.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
log r3.yzw, r3.yyzw
mul r3.yzw, r3.yyzw, r5.xxyz
exp r3.yzw, r3.yyzw
movc r1.yzw, r1.yyyy, r3.yyzw, r4.xxyz
add r2.z, -r1.x, l(1.000000)
mul r3.yzw, r1.xxxx, r4.xxyz
mad r1.xyz, r1.yzwy, r2.zzzz, r3.yzwy
add r3.yzw, -r1.xxyz, cb0[21].xxyz
mad r3.yzw, cb0[21].wwww, r3.yyzw, r1.xxyz
mad r1.w, -r2.x, r3.x, l(1.000000)
mul r3.yzw, r1.wwww, r3.yyzw
mad r1.xyz, r1.xyzx, r2.yyyy, r3.yzwy
add r1.w, -cb0[40].x, l(1.000000)
add_sat r2.yzw, r1.wwww, cb0[39].xxyz
mul r3.yzw, r1.xxyz, r2.yyzw
mad r4.xy, v10.xyxx, v0.xyxx, v10.zwzz
add r4.z, -r4.y, l(1.000000)
sample r4.xyzw, r4.xzxx, t2.xyzw, s2
mad r5.xy, r2.xxxx, r3.xxxx, -v12.zwzz
mul r5.xy, r5.xyxx, v12.xyxx
ge r5.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xyxx
mul r1.w, r4.w, |v12.x|
mad r1.xyz, -r1.xyzx, r2.yzwy, r4.xyzx
mad r1.xyz, r1.wwww, r1.xyzx, r3.yzwy
movc r1.xyz, r5.xxxx, r1.xyzx, r3.yzwy
mad r2.xy, v11.xyxx, v0.xyxx, v11.zwzz
add r2.z, -r2.y, l(1.000000)
sample r2.xyzw, r2.xzxx, t3.xyzw, s3
mul r1.w, r2.w, |v12.y|
add r2.xyz, -r1.xyzx, r2.xyzx
mad r2.xyz, r1.wwww, r2.xyzx, r1.xyzx
movc r1.xyz, r5.yyyy, r2.xyzx, r1.xyzx
mul r1.w, r0.w, v4.y
add r1.xyz, r1.xyzx, -v5.xyzx
mad r1.xyz, v2.zzzz, r1.xyzx, v5.xyzx
mul r2.x, v0.x, cb0[36].w
mad r2.z, -v0.y, cb0[37].w, l(1.000000)
add r2.xy, r2.xzxx, -cb0[38].xyxx
mul r2.xy, r2.xyxx, l(1.000000, 0.562500, 0.000000, 0.000000)
dp2 r2.x, r2.xyxx, r2.xyxx
sqrt r2.x, r2.x
add r2.x, r2.x, -cb0[38].z
add r2.y, -cb0[38].z, cb0[38].w
div_sat r2.x, r2.x, r2.y
add r2.yzw, -cb0[36].xxyz, cb0[37].xxyz
mad r2.xyz, r2.xxxx, r2.yzwy, cb0[36].xyzx
mul o0.xyz, r1.xyzx, r2.xyzx
mov o0.w, r1.w
mov o1.xy, v4.wzww
mov o1.z, v5.w
mov o1.w, r1.w
mov o2.xyzw, r0.xyzw
ret 
// Approximately 118 instruction slots used
 