//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer perMaterialBuffer
// {
//
//   float4 g_commonParam;              // Offset:    0 Size:    16
//   float4 g_fogColor;                 // Offset:   16 Size:    16
//   float4 g_fogParam;                 // Offset:   32 Size:    16 [unused]
//   float4 g_ambientColor;             // Offset:   48 Size:    16 [unused]
//   float4 g_lightDirection;           // Offset:   64 Size:    16 [unused]
//   row_major float4x4 g_matWorldViewProj;// Offset:   80 Size:    64 [unused]
//   float4 g_uvOffset0;                // Offset:  144 Size:    16 [unused]
//   float4 g_uvOffset1;                // Offset:  160 Size:    16 [unused]
//   float4 g_blendRate;                // Offset:  176 Size:    16 [unused]
//   float4 g_blendType;                // Offset:  192 Size:    16 [unused]
//   float4 g_multColor;                // Offset:  208 Size:    16 [unused]
//   row_major float4x4 g_matShadowProj0;// Offset:  224 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj1;// Offset:  288 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj2;// Offset:  352 Size:    64 [unused]
//   row_major float4x4 g_matShadowProj3;// Offset:  416 Size:    64 [unused]
//   float4 g_shadowParam;              // Offset:  480 Size:    16
//   float4 g_shadowColor;              // Offset:  496 Size:    16
//   float4 g_ScreenToUV;               // Offset:  512 Size:    16
//   float4 g_uvOffset3;                // Offset:  528 Size:    16
//   float4 g_uvOffsetScreen;           // Offset:  544 Size:    16
//   float4 g_uvScaleScreen;            // Offset:  560 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_sampler0                        sampler      NA          NA    0        1
// g_samplerScreen0                  sampler      NA          NA    1        1
// g_samplerScreen1                  sampler      NA          NA    2        1
// g_samplerShadow                   sampler      NA          NA    3        1
// g_texture0                        texture  float4          2d    0        1
// g_texture2                        texture  float4          2d    1        1
// g_texture3                        texture  float4          2d    2        1
// g_textureShadow                   texture  float4          2d    3        1
// perMaterialBuffer                 cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1     z         2     NONE   float     z 
// TEXCOORD                 5      w        2     NONE   float      w
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 9   xyzw        6     NONE   float   xyzw
// COLOR                    1   xyzw        7     NONE   float      w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer cb0[36], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_input_ps linear v2.z
dcl_input_ps linear v2.w
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyzw
dcl_input_ps linear v7.w
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 8
sample r0.xyzw, v2.xyxx, t0.xyzw, s0
mul r0.xyzw, r0.xyzw, v1.xyzw
lt r1.x, cb0[30].z, v7.w
div r1.yzw, v6.xxyz, v6.wwww
sample r2.xyzw, r1.yzyy, t3.xyzw, s3
div r3.xyz, v5.xyzx, v5.wwww
sample r4.xyzw, r3.xyxx, t3.xyzw, s3
div r3.xyw, v4.xyxz, v4.wwww
sample r5.xyzw, r3.xyxx, t3.xyzw, s3
div r6.xyz, v3.xyzx, v3.wwww
sample r7.xyzw, r6.xyxx, t3.xyzw, s3
if_nz r1.x
  ge r1.x, r2.x, r1.w
  ne r1.y, r2.x, l(0.000000)
  and r1.x, r1.y, r1.x
  mad r1.y, -r2.x, r2.x, r2.y
  add r1.z, -r1.w, r2.x
  mad_sat r2.z, |r1.z|, l(3.000000), l(-0.300000)
  add r1.y, r1.y, l(-0.000020)
  mad r1.y, r2.z, r1.y, l(0.000020)
  mad r1.z, r1.z, r1.z, r1.y
  max r1.z, r1.z, l(0.000000)
  div r1.y, r1.y, r1.z
  add r1.y, r1.y, l(-0.000100)
  mul_sat r1.y, r1.y, l(1.000100)
  movc r1.x, r1.x, l(1.000000), r1.y
else 
  lt r1.y, cb0[30].y, v7.w
  if_nz r1.y
    ge r1.y, r2.x, r1.w
    ne r1.z, r2.x, l(0.000000)
    and r1.y, r1.z, r1.y
    mad r1.z, -r2.x, r2.x, r2.y
    add r1.w, -r1.w, r2.x
    mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
    add r1.z, r1.z, l(-0.000020)
    mad r1.z, r2.x, r1.z, l(0.000020)
    mad r1.w, r1.w, r1.w, r1.z
    max r1.w, r1.w, l(0.000000)
    div r1.z, r1.z, r1.w
    add r1.z, r1.z, l(-0.000100)
    mul_sat r1.z, r1.z, l(1.000100)
    movc r1.y, r1.y, l(1.000000), r1.z
    ge r1.z, r4.x, r3.z
    ne r1.w, r4.x, l(0.000000)
    and r1.z, r1.w, r1.z
    mad r1.w, -r4.x, r4.x, r4.y
    add r2.x, -r3.z, r4.x
    mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
    add r1.w, r1.w, l(-0.000020)
    mad r1.w, r2.y, r1.w, l(0.000020)
    mad r2.x, r2.x, r2.x, r1.w
    max r2.x, r2.x, l(0.000000)
    div r1.w, r1.w, r2.x
    add r1.w, r1.w, l(-0.000100)
    mul_sat r1.w, r1.w, l(1.000100)
    movc r1.z, r1.z, l(1.000000), r1.w
    add r1.w, cb0[30].z, l(-200.000000)
    add r1.w, -r1.w, v7.w
    mul_sat r1.w, r1.w, l(0.005000)
    add r1.y, -r1.z, r1.y
    mad r1.x, r1.w, r1.y, r1.z
  else 
    lt r1.y, cb0[30].x, v7.w
    if_nz r1.y
      ge r1.y, r4.x, r3.z
      ne r1.z, r4.x, l(0.000000)
      and r1.y, r1.z, r1.y
      mad r1.z, -r4.x, r4.x, r4.y
      add r1.w, -r3.z, r4.x
      mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
      add r1.z, r1.z, l(-0.000020)
      mad r1.z, r2.x, r1.z, l(0.000020)
      mad r1.w, r1.w, r1.w, r1.z
      max r1.w, r1.w, l(0.000000)
      div r1.z, r1.z, r1.w
      add r1.z, r1.z, l(-0.000100)
      mul_sat r1.z, r1.z, l(1.000100)
      movc r1.y, r1.y, l(1.000000), r1.z
      ge r1.z, r5.x, r3.w
      ne r1.w, r5.x, l(0.000000)
      and r1.z, r1.w, r1.z
      mad r1.w, -r5.x, r5.x, r5.y
      add r2.x, -r3.w, r5.x
      mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
      add r1.w, r1.w, l(-0.000020)
      mad r1.w, r2.y, r1.w, l(0.000020)
      mad r2.x, r2.x, r2.x, r1.w
      max r2.x, r2.x, l(0.000000)
      div r1.w, r1.w, r2.x
      add r1.w, r1.w, l(-0.000100)
      mul_sat r1.w, r1.w, l(1.000100)
      movc r1.z, r1.z, l(1.000000), r1.w
      add r1.w, cb0[30].y, l(-200.000000)
      add r1.w, -r1.w, v7.w
      mul_sat r1.w, r1.w, l(0.005000)
      add r1.y, -r1.z, r1.y
      mad r1.x, r1.w, r1.y, r1.z
    else 
      ge r1.y, r5.x, r3.w
      ne r1.z, r5.x, l(0.000000)
      and r1.y, r1.z, r1.y
      mad r1.z, -r5.x, r5.x, r5.y
      add r1.w, -r3.w, r5.x
      mad_sat r2.x, |r1.w|, l(3.000000), l(-0.300000)
      add r1.z, r1.z, l(-0.000020)
      mad r1.z, r2.x, r1.z, l(0.000020)
      mad r1.w, r1.w, r1.w, r1.z
      max r1.w, r1.w, l(0.000000)
      div r1.z, r1.z, r1.w
      add r1.z, r1.z, l(-0.000100)
      mul_sat r1.z, r1.z, l(1.000100)
      movc r1.y, r1.y, l(1.000000), r1.z
      ge r1.z, r7.x, r6.z
      ne r1.w, r7.x, l(0.000000)
      and r1.z, r1.w, r1.z
      mad r1.w, -r7.x, r7.x, r7.y
      add r2.x, -r6.z, r7.x
      mad_sat r2.y, |r2.x|, l(3.000000), l(-0.300000)
      add r1.w, r1.w, l(-0.000020)
      mad r1.w, r2.y, r1.w, l(0.000020)
      mad r2.x, r2.x, r2.x, r1.w
      max r2.x, r2.x, l(0.000000)
      div r1.w, r1.w, r2.x
      add r1.w, r1.w, l(-0.000100)
      mul_sat r1.w, r1.w, l(1.000100)
      movc r1.z, r1.z, l(1.000000), r1.w
      add r1.w, cb0[30].x, l(-200.000000)
      add r1.w, -r1.w, v7.w
      mul_sat r1.w, r1.w, l(0.005000)
      add r1.y, -r1.z, r1.y
      mad r1.x, r1.w, r1.y, r1.z
    endif 
  endif 
endif 
ge r1.y, cb0[0].x, r0.w
discard_nz r1.y
add r1.y, -v7.w, cb0[30].w
mul_sat r1.y, r1.y, l(0.002000)
add r1.x, r1.x, l(-1.000000)
mad r1.x, r1.y, r1.x, l(1.000000)
mad_sat r1.y, v2.w, l(3.000000), cb0[31].w
mul r1.x, r1.y, r1.x
add r1.yzw, -cb0[31].xxyz, l(0.000000, 1.000000, 1.000000, 1.000000)
mad r1.xyz, r1.xxxx, r1.yzwy, cb0[31].xyzx
mul r2.xyz, r0.xyzx, r1.xyzx
mov r3.x, l(1.000000)
mov r3.yz, cb0[32].yyxy
mul r4.xyzw, r3.xyxy, cb0[35].xyzw
mov r3.w, v0.y
mul r3.xyzw, r3.zwzw, r4.xyzw
mul r4.xyzw, cb0[34].xyzw, cb0[35].xyzw
mov r5.x, v0.x
mov r5.y, l(-1.000000)
mad r6.xy, r3.xyxx, r5.xyxx, r4.xyxx
add r6.z, -r6.y, l(1.000000)
sample r6.xyzw, r6.xzxx, t1.xyzw, s1
mul r1.w, r6.w, cb0[33].x
mad r0.xyz, -r0.xyzx, r1.xyzx, r6.xyzx
mad r0.xyz, r1.wwww, r0.xyzx, r2.xyzx
mad r1.xy, r3.zwzz, r5.xyxx, r4.zwzz
add r1.z, -r1.y, l(1.000000)
sample r1.xyzw, r1.xzxx, t2.xyzw, s2
mul r1.w, r1.w, cb0[33].y
add r1.xyz, -r0.xyzx, r1.xyzx
mad r0.xyz, r1.wwww, r1.xyzx, r0.xyzx
mul r0.w, r0.w, cb0[0].y
add r0.xyz, r0.xyzx, -cb0[1].xyzx
mad o0.xyz, v2.zzzz, r0.xyzx, cb0[1].xyzx
mov o0.w, r0.w
mov o1.xy, cb0[0].wzww
mov o1.z, l(0.990000)
mov o1.w, r0.w
ret 
// Approximately 174 instruction slots used
 