"""Generate and compile the generic Storm effect shaders for GMod's screenspace_general.

One vertex shader and three pixel-shader variants translate the game's effect
shader family (keys xxF002 / xxF007 with zero, one or two screen-film layers):

  game VS  clip = pos * WVP; colour = vertex * g_multColor * g_ambientColor;
           uv = uv * g_uvOffset0.zw + g_uvOffset0.xy;
           fog = 1 + g_fogParam.z * (saturate((g_fogParam.y - w) / (g_fogParam.y - g_fogParam.x)) - 1)
  game PS  tex = sample(base, uv); alpha = tex.a * colour.a; discard if g_commonParam.x >= alpha;
           rgb = tex.rgb * colour.rgb; each film: rgb = lerp(rgb, film.rgb, film.a * g_uvOffset3[i]) with
           film uv = SV_Position.xy * g_ScreenToUV.xy * (sx, -sy) + g_uvOffsetScreen * g_uvScaleScreen, v flipped;
           out = (g_fogColor + fog * (rgb - g_fogColor), alpha * g_commonParam.y)

screenspace_general only offers pixel constants c0-c3 and no custom vertex
constants, so per-draw values use c0-c3 and per-material values ride on
TEXCOORD1-6 of the cached mesh:
  c0 g_uvOffset0   c1 (multColor*ambient).rgb, g_commonParam.x
  c2 g_uvOffsetScreen   c3 g_fogColor.rgb, g_commonParam.y
  TEXCOORD1/2 g_uvScaleScreen.xy/.zw   TEXCOORD3 g_uvOffset3.xy
  TEXCOORD4 fog start, end   TEXCOORD5 fog strength, 0   TEXCOORD6 1/width, 1/height
  TEXCOORD7 base-texture address codes (mirror / border, see the pixel shader)
Fog is evaluated per pixel from the interpolated clip w, which equals the
game's per-vertex value wherever the saturate does not clip inside a triangle.
verify_port_shaders.py checks every variant against the game's bytecode.
"""

from __future__ import annotations

import json
from pathlib import Path

from compile_source_shader import ROOT, compile as compile_hlsl, package

SHADERS = ROOT / 'shaders'
ADDON_FXC = ROOT.parent / 'storm_amaterasu_lab' / 'shaders' / 'fxc'

VERTEX = '''// Generated by build_storm_fx_shaders.py. Generic Storm effect vertex shader.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float4 color : COLOR0;
    float2 uv : TEXCOORD0;
    float2 filmScaleXY : TEXCOORD1;
    float2 filmScaleZW : TEXCOORD2;
    float2 filmWeight : TEXCOORD3;
    float2 fogRange : TEXCOORD4;
    float2 fogStrength : TEXCOORD5;
    float2 screen : TEXCOORD6;
    float2 address : TEXCOORD7;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uvw : TEXCOORD0;        // uv, clip w, fog strength
    float4 filmScale : TEXCOORD1;  // g_uvScaleScreen
    float4 filmFog : TEXCOORD2;    // g_uvOffset3.xy, fog start, fog end
    float4 screen : TEXCOORD3;     // 1/width, 1/height, base-texture address codes
    float4 color : TEXCOORD4;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    // Source's cModelViewProj takes a row vector on the left.
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uvw = float4(i.uv, o.position.w, i.fogStrength.x);
    o.filmScale = float4(i.filmScaleXY, i.filmScaleZW);
    o.filmFog = float4(i.filmWeight, i.fogRange);
    o.screen = float4(i.screen, i.address);
    o.color = i.color;
    return o;
}
'''

PIXEL = '''// Generated by build_storm_fx_shaders.py. Generic Storm effect pixel shader, FILM = {film}.
sampler TexBase : register(s0);
sampler TexFilm0 : register(s1);
sampler TexFilm1 : register(s2);
float4 Atlas : register(c0);          // g_uvOffset0
float4 TintThreshold : register(c1);  // g_multColor.rgb * g_ambientColor.rgb, g_commonParam.x
float4 FilmOffset : register(c2);     // g_uvOffsetScreen
float4 FogAlpha : register(c3);       // g_fogColor.rgb, g_commonParam.y
struct PS_INPUT {{
    float4 uvw : TEXCOORD0;
    float4 filmScale : TEXCOORD1;
    float4 filmFog : TEXCOORD2;
    float4 screen : TEXCOORD3;
    float4 color : TEXCOORD4;
    float2 pixel : VPOS;
}};
float4 main(PS_INPUT i) : COLOR {{
    // Base-texture addressing the VTF cannot express. Per axis: 0 = as the VTF
    // says (wrap, or clamp for the *_c variants), < 0 = mirror, > 0 = border
    // (0,0,0,0) with the value being the texture size. Both run on a clamped
    // VTF and equal D3D bilinear filtering at mip 0, the only mip the game's
    // effect samplers reach (LOD bias -16).
    float2 uv = i.uvw.xy * Atlas.zw + Atlas.xy;
    float2 address = i.screen.zw;
    float2 mirrored = 1 - abs(frac(uv * 0.5) * 2 - 1);
    uv = address < 0 ? mirrored : uv;
    float4 tex = tex2D(TexBase, uv);
    float2 inside = saturate(uv * address + 0.5) * saturate((1 - uv) * address + 0.5);
    inside = address > 0 ? inside : 1;
    tex *= inside.x * inside.y;
    float alpha = tex.a * i.color.a;
    clip(TintThreshold.w >= alpha ? -1 : 1);
    float3 rgb = tex.rgb * (i.color.rgb * TintThreshold.rgb);
{films}    float fog = 1 + i.uvw.w * (saturate((i.filmFog.w - i.uvw.z) / (i.filmFog.w - i.filmFog.z)) - 1);
    rgb = FogAlpha.rgb + fog * (rgb - FogAlpha.rgb);
    return float4(rgb, alpha * FogAlpha.a);
}}
'''

FILM0 = '''    // D3D9 vPos is the integer pixel; the game's SV_Position is its centre.
    float2 screenUV = (i.pixel + 0.5) * i.screen.xy;
    float2 uv0 = screenUV * float2(i.filmScale.x, -i.filmScale.y) + FilmOffset.xy * i.filmScale.xy;
    uv0.y = 1 - uv0.y;
    float4 film0 = tex2D(TexFilm0, uv0);
    rgb += (film0.a * i.filmFog.x) * (film0.rgb - rgb);
'''
FILM1 = '''    float2 uv1 = screenUV * float2(i.filmScale.z, -i.filmScale.w) + FilmOffset.zw * i.filmScale.zw;
    uv1.y = 1 - uv1.y;
    float4 film1 = tex2D(TexFilm1, uv1);
    rgb += (film1.a * i.filmFog.y) * (film1.rgb - rgb);
'''

# Shader key xxF008 (game pair 01f008): the base shader plus a view-angle
# falloff. game VS: n = normal * g_matWorldViewInvTrans; game PS:
#   u = min(|n.z| / |n|, 1); alpha *= sample(falloff, (u, g_uvOffset2.x)).g
# Without vertex constants the port takes the view axis expressed in model
# space as a pixel constant; n.z / |n| equals dot(N, axis) / |N| whenever the
# world matrix scales uniformly, which the player asserts.
FALLOFF_VERTEX = '''// Generated by build_storm_fx_shaders.py. Storm effect vertex shader, falloff variant.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float3 normal : NORMAL;
    float4 color : COLOR0;
    float2 uv : TEXCOORD0;
    float2 fogRange : TEXCOORD4;
    float2 fogStrength : TEXCOORD5;
    float2 address : TEXCOORD7;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uvw : TEXCOORD0;        // uv, clip w, fog strength
    float4 normal : TEXCOORD1;     // model-space normal
    float4 filmFog : TEXCOORD2;    // 0, 0, fog start, fog end
    float4 screen : TEXCOORD3;     // 0, 0, base-texture address codes
    float4 color : TEXCOORD4;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uvw = float4(i.uv, o.position.w, i.fogStrength.x);
    o.normal = float4(i.normal, 0);
    o.filmFog = float4(0, 0, i.fogRange);
    o.screen = float4(0, 0, i.address);
    o.color = i.color;
    return o;
}
'''

FALLOFF_PIXEL = '''// Generated by build_storm_fx_shaders.py. Storm effect pixel shader, falloff variant.
sampler TexBase : register(s0);
sampler TexFalloff : register(s1);
float4 Atlas : register(c0);          // g_uvOffset0
float4 TintThreshold : register(c1);  // g_multColor.rgb * g_ambientColor.rgb, g_commonParam.x
float4 ViewAxis : register(c2);       // view z axis in model space, g_uvOffset2.x
float4 FogAlpha : register(c3);       // g_fogColor.rgb, g_commonParam.y
struct PS_INPUT {
    float4 uvw : TEXCOORD0;
    float4 normal : TEXCOORD1;
    float4 filmFog : TEXCOORD2;
    float4 screen : TEXCOORD3;
    float4 color : TEXCOORD4;
};
float4 main(PS_INPUT i) : COLOR {
    float2 uv = i.uvw.xy * Atlas.zw + Atlas.xy;
    float2 address = i.screen.zw;
    float2 mirrored = 1 - abs(frac(uv * 0.5) * 2 - 1);
    uv = address < 0 ? mirrored : uv;
    float4 tex = tex2D(TexBase, uv);
    float2 inside = saturate(uv * address + 0.5) * saturate((1 - uv) * address + 0.5);
    inside = address > 0 ? inside : 1;
    tex *= inside.x * inside.y;
    float3 n = i.normal.xyz;
    float facing = min(abs(dot(n, ViewAxis.xyz) * rsqrt(dot(n, n))), 1);
    float4 falloff = tex2D(TexFalloff, float2(facing, ViewAxis.w));
    float alpha = tex.a * i.color.a * falloff.g;
    clip(TintThreshold.w >= alpha ? -1 : 1);
    float3 rgb = tex.rgb * (i.color.rgb * TintThreshold.rgb);
    float fog = 1 + i.uvw.w * (saturate((i.filmFog.w - i.uvw.z) / (i.filmFog.w - i.filmFog.z)) - 1);
    rgb = FogAlpha.rgb + fog * (rgb - FogAlpha.rgb);
    return float4(rgb, alpha * FogAlpha.a);
}
'''

# Shader key 03F009 (game pair 3dc10cf4 / 4bf6e191): screen refraction.
#   offset = (nA.xy + nB.xy - 1) * strength * mask.a * 2, strength = g_commonParam.y * g_uvOffset1.z * colour.r
#   out = scene(SV_Position.xy * g_ScreenToUV.xy + (offset.x, -offset.y)), alpha = colour.a
# The game keeps the undisplaced pixel when the displaced sample lies in front
# of the surface (scene depth test); the port has no scene depth and always
# displaces. verify_port_shaders.py reports how many pixels that changes.
DISTORT_VERTEX = '''// Generated by build_storm_fx_shaders.py. Storm effect vertex shader, refraction variant.
float4x4 ModelViewProjection : register(c4);
struct VS_INPUT {
    float4 position : POSITION;
    float4 color : COLOR0;
    float2 uv0 : TEXCOORD0;
    float2 uv1 : TEXCOORD1;
    float2 screen : TEXCOORD6;
};
struct VS_OUTPUT {
    float4 position : POSITION;
    float4 uv : TEXCOORD0;
    float4 screen : TEXCOORD1;
    float4 color : TEXCOORD2;
};
VS_OUTPUT main(VS_INPUT i) {
    VS_OUTPUT o;
    o.position = mul(float4(i.position.xyz, 1), ModelViewProjection);
    o.uv = float4(i.uv0, i.uv1);
    o.screen = float4(i.screen, 0, 0);
    o.color = i.color;
    return o;
}
'''

DISTORT_PIXEL = '''// Generated by build_storm_fx_shaders.py. Storm effect pixel shader, refraction variant.
sampler TexNormal : register(s0);
sampler TexScene : register(s1);
float4 Offset0 : register(c0);      // g_uvOffset0
float4 Offset1 : register(c1);      // g_uvOffset1.xy, g_commonParam.y * g_uvOffset1.z, 0
float4 ScaleNormal : register(c2);  // g_uvScaleNormal
float4 ScaleAlpha : register(c3);   // g_uvScaleAlpha.xy, 0, 0
struct PS_INPUT {
    float4 uv : TEXCOORD0;
    float4 screen : TEXCOORD1;
    float4 color : TEXCOORD2;
    float2 pixel : VPOS;
};
float4 main(PS_INPUT i) : COLOR {
    float2 uvA = i.uv.xy * ScaleNormal.xy + Offset0.xy * float2(1, -1);
    float2 uvB = i.uv.yx * ScaleNormal.wz + float2(-Offset1.y, Offset1.x);
    float2 uvC = i.uv.zw * ScaleAlpha.xy + Offset0.zw * float2(1, -1);
    float2 bend = tex2D(TexNormal, uvA).xy + tex2D(TexNormal, uvB).xy - 1;
    bend *= Offset1.z * i.color.r;
    bend *= tex2D(TexNormal, uvC).a;
    bend += bend;
    float2 screenUV = (i.pixel + 0.5) * i.screen.xy + float2(bend.x, -bend.y);
    return float4(tex2D(TexScene, screenUV).rgb, i.color.a);
}
'''

# Stage tone control (game pixel shader 81206c57, first pass of the post chain,
# constants paramR / paramG / paramB / hparam / lparam). Per pixel:
#   c += (2 - 2c) * (paramR.x, paramG.y, paramB.z) * 2/3
#   low = c + lparam.rgb * min(saturate(0.35 - luma) * 5.714286, 1)
#   c = lerp(low, c + hparam.rgb, min(saturate(luma - 0.65) * 5.714286, 1))
#   to HSV, saturation = max(saturation + lparam.w, 0), back to RGB
# The game divides by zero on grey and black pixels and relies on D3D11 NaN
# rules (saturate(NaN) = 0, max(NaN, 0) = 0); the port spells those cases out.
TONE_PIXEL = '''// Generated by build_storm_fx_shaders.py. Storm stage tone control.
sampler Scene : register(s0);
float4 Shift : register(c0);    // paramR.x, paramG.y, paramB.z, lparam.w
float4 Low : register(c1);      // lparam.rgb
float4 High : register(c2);     // hparam.rgb
float4 Texel : register(c3);    // 1/width, 1/height
float4 main(float2 pixel : VPOS) : COLOR {
    float3 c = tex2D(Scene, (pixel + 0.5) * Texel.xy).rgb;
    c += (1 - (c - 0.5) * 2) * Shift.xyz * 0.666667;
    float luma = dot(c, float3(0.298912, 0.586611, 0.114478));
    float dark = min(saturate(0.35 - luma) * 5.714286, 1);
    float bright = min(saturate(luma - 0.65) * 5.714286, 1);
    float3 low = c + dark * Low.rgb;
    c = low + bright * (c + High.rgb - low);
    float4 p = c.g < c.b ? float4(c.b, c.g, -1, 0.666667) : float4(c.g, c.b, 0, -0.333333);
    float4 q = c.r < p.x ? float4(p.x, p.y, p.w, c.r) : float4(c.r, p.y, p.z, p.x);
    float chroma = q.x - min(q.w, q.y);
    float3 hue = -1;
    if (chroma != 0) {
        float h = abs((q.w - q.y) / (chroma * 6) + q.z);
        hue = saturate(abs(frac(h + float3(1, 0.666667, 0.333333)) * 6 - 3) - 1) - 1;
    }
    float saturation = q.x != 0 ? max(chroma / q.x + Shift.w, 0) : 0;
    return float4((saturation * hue + 1) * q.x, 1);
}
'''

SOURCES = {
    'storm_tone_ps30': TONE_PIXEL,
    'storm_fx_vs30': VERTEX,
    'storm_fx_ps30': PIXEL.format(film=0, films=''),
    'storm_fx_film1_ps30': PIXEL.format(film=1, films=FILM0),
    'storm_fx_film2_ps30': PIXEL.format(film=2, films=FILM0 + FILM1),
    'storm_fx_falloff_vs30': FALLOFF_VERTEX,
    'storm_fx_falloff_ps30': FALLOFF_PIXEL,
    'storm_fx_distort_vs30': DISTORT_VERTEX,
    'storm_fx_distort_ps30': DISTORT_PIXEL,
}

if __name__ == '__main__':
    manifest = []
    ADDON_FXC.mkdir(parents=True, exist_ok=True)
    for name, text in SOURCES.items():
        source = SHADERS / f'{name}.hlsl'
        source.write_text(text, encoding='ascii')
        target = 'vs_3_0' if name.endswith('_vs30') else 'ps_3_0'
        code = compile_hlsl(source, target)
        source.with_suffix('.bin').write_bytes(code)
        raw = package(code, source.read_bytes())
        (ADDON_FXC / f'{name}.vcs').write_bytes(raw)
        manifest.append({'name': name, 'target': target, 'bytecode': len(code), 'package': len(raw)})
        print(f'compiled {name} ({target}): {len(code)} bytes')
    (ROOT / 'captured_assets/procedural/storm_fx_shader_build.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
