"""Print the nuccChunkModel header (bytes before the NDP3 payload) of effect models.

The header carries per-model render attributes that the NUD material does not:
captures show stage fog / stage ambient applied per model, so this is where the
selector should live. Output is raw, with no interpretation applied.
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path

from decode_billboards import decode
from inspect_page_refs import resolve, table
from xfbin_chunks import parse

ROOT = Path(__file__).resolve().parent
ARCHIVES = [ROOT / 'captured_assets/data/effect/4efb_amt1.xfbin', ROOT / 'extracted/data/effect/1efcmn.xfbin']


def headers(path: Path) -> list[dict]:
    data, chunks = parse(path)
    refs = table(data)
    owners: dict[str, list[str]] = {}
    scratch = ROOT / 'captured_assets/procedural/billboards'
    for c in chunks:
        if c['type'] != 'nuccChunkBillboard':
            continue
        target = scratch / (c['name'] + '.bin')
        if not target.exists():
            continue
        board = decode(target)
        kind, _, model = resolve(refs, c['page'] + board['header']['resource_page_index'])
        if kind == 'nuccChunkModel':
            owners.setdefault(model, []).append(c['name'])
    # nuccChunkCoord of the same name: position, rotation, scale (3 floats each),
    # then one float that multiplies the model's alpha (node opacity).
    coords = {}
    for c in chunks:
        if c['type'] == 'nuccChunkCoord' and c['size'] >= 40:
            values = struct.unpack_from('>10f', data, c['offset'])
            coords[c['name']] = {'position': values[0:3], 'rotation': values[3:6], 'scale': values[6:9], 'opacity': values[9]}
    out = []
    for c in chunks:
        if c['type'] != 'nuccChunkModel':
            continue
        body = data[c['offset']:c['offset'] + c['size']]
        at = body.find(b'NDP3')
        if at < 0:
            continue
        head = body[:at]
        out.append({'archive': path.name, 'model': c['name'], 'billboards': owners.get(c['name'], []),
                    'header_size': at, 'header_hex': head.hex(), 'coord': coords.get(c['name']),
                    'bytes': list(head[:16]), 'trailer_size': len(body) - at - struct.unpack_from('>I', body, at + 4)[0]})
    return out


LUA_HEADER = '''-- Generated by inspect_model_chunk_headers.py from the original xfbin files.
-- nuccChunkModel header bytes 5, 6, 7 of every effect model, keyed by model name
-- and by the billboard that references it (runtime copies: model +29, +2A, +2B).
--   layer  the draw-command layer (0x1413651e0); fog comes from the render
--          context that layer is submitted in (context +20)
--   light  index of the context light set whose ambient the shader receives
--          (0x141312a90 on context +38); set 4 held the stage ambient, set 1 white
-- attributes is kept raw; its bits are not decoded.
-- opacity is the tenth float of the model's nuccChunkCoord. The captured
-- g_commonParam.y of clump draws equals particle alpha * opacity (light00 0.9
-- on six values, nor_dst03 0.5, shock09 1.0). Billboards carry the same value
-- as billboard channel 4, which the player already applies; do not apply both.
'''


def write_lua(rows: list[dict], wanted: set[str], target: Path) -> None:
    lines = []
    for r in rows:
        for name in sorted({r['model'], *r['billboards']} & wanted):
            b = r['bytes']
            opacity = f",opacity={r['coord']['opacity']:.9g}" if r['coord'] else ''
            lines.append(f"['{name}']={{attributes={b[5]},layer={b[6]},light={b[7]},model='{r['model']}'{opacity}}},")
    target.write_text(LUA_HEADER + 'return {\n' + '\n'.join(sorted(lines)) + '\n}\n', encoding='ascii')


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--output', type=Path, default=ROOT / 'captured_assets/procedural/model_chunk_headers.json')
    ap.add_argument('--lua', type=Path, default=ROOT.parent / 'storm_amaterasu_lab/lua/storm_amt_lab/model_context_data.lua')
    args = ap.parse_args()
    rows = [row for path in ARCHIVES for row in headers(path)]
    args.output.write_text(json.dumps(rows, indent=2) + '\n', encoding='utf-8')
    graphs = json.loads((ROOT / 'captured_assets/particle_graph.json').read_text())
    wanted = {r['name'] for g in graphs for e in g['emitters'] for r in e['resources']} | {'4efb_amt15'}
    write_lua(rows, wanted, args.lua)
    print('WROTE:', args.lua)
    rows = [r for r in rows if {r['model'], *r['billboards']} & wanted]
    for r in rows:
        print(f"{r['archive']:16} {r['model']:28} {str(r['billboards']):34} head {r['header_size']:3} {r['header_hex'][:56]} trailer {r['trailer_size']}")
