-- Generated by inspect_model_chunk_headers.py from the original xfbin files.
-- nuccChunkModel header bytes 5, 6, 7 of every effect model, keyed by model name
-- and by the billboard that references it (runtime copies: model +29, +2A, +2B).
--   layer  the draw-command layer (0x1413651e0); fog comes from the render
--          context that layer is submitted in (context +20)
--   light  index of the context light set whose ambient the shader receives
--          (0x141312a90 on context +38); set 4 held the stage ambient, set 1 white
-- attributes is kept raw; its bits are not decoded.
-- opacity is the tenth float of the model's nuccChunkCoord. The captured
-- g_commonParam.y of clump draws equals particle alpha * opacity (light00 0.9
-- on six values, nor_dst03 0.5, shock09 1.0). Billboards carry the same value
-- as billboard channel 4, which the player already applies; do not apply both.
return {
['1efc_fire03a']={attributes=6,layer=3,light=1,model='1efc_fire03a',opacity=1},
['1efc_nor_dst03']={attributes=4,layer=14,light=0,model='1efc_nor_dst03',opacity=0.5},
['1efc_part09b']={attributes=1,layer=0,light=4,model='1efc_part09b',opacity=0.899999976},
['1efc_part11b']={attributes=3,layer=1,light=1,model='1efc_part11b',opacity=0.899999976},
['1efc_shock09']={attributes=6,layer=1,light=1,model='1efc_shock09',opacity=1},
['4efb_amt00']={attributes=3,layer=18,light=1,model='4efb_amt00',opacity=1},
['4efb_amt01']={attributes=3,layer=18,light=1,model='4efb_amt01',opacity=1},
['4efb_amt02']={attributes=3,layer=18,light=1,model='4efb_amt02',opacity=1},
['4efb_amt03']={attributes=3,layer=18,light=1,model='4efb_amt03',opacity=1},
['4efb_amt04']={attributes=3,layer=18,light=1,model='4efb_amt04',opacity=1},
['4efb_amt05']={attributes=3,layer=18,light=1,model='4efb_amt05',opacity=1},
['4efb_amt06']={attributes=3,layer=18,light=1,model='4efb_amt06',opacity=1},
['4efb_amt07']={attributes=3,layer=18,light=1,model='4efb_amt07',opacity=1},
['4efb_amt08']={attributes=1,layer=2,light=1,model='4efb_amt08',opacity=1},
['4efb_amt09']={attributes=3,layer=18,light=1,model='4efb_amt09',opacity=1},
['4efb_amt10']={attributes=3,layer=18,light=1,model='4efb_amt10',opacity=1},
['4efb_amt11']={attributes=1,layer=2,light=1,model='4efb_amt11',opacity=1},
['4efb_amt12']={attributes=1,layer=2,light=1,model='4efb_amt12',opacity=1},
['4efb_amt13']={attributes=1,layer=2,light=1,model='4efb_amt13',opacity=1},
['4efb_amt14']={attributes=1,layer=2,light=1,model='4efb_amt14',opacity=1},
['4efb_amt15']={attributes=6,layer=1,light=1,model='4efb_amt15',opacity=1},
['4efb_light00']={attributes=6,layer=1,light=1,model='4efb_light00',opacity=0.899999976},
}
